apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildah-pipeline
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-cohort/emea-8-piotr-biskupski-buildah-express-app
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-data
    - name: buildah
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
      - name: IMAGE
        value: quay.io/pbworker/pb-node-assignemnt:2
      workspaces:
      - name: source
        workspace: shared-data
      runAfter:
        - git-clone
